-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC import sys
-- MAGIC
-- MAGIC sys.path.append("/Workspace/Users/ketanchoudhary1011@gmail.com/NoteBook/databricks-code-repo/Databricks_workouts_2025/7_lakeflow_declarative_pipeline/first_lakeflow_etl_declarative_dlt_pipeline_wd36")

-- COMMAND ----------

-- !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

USE CATALOG `workspace`;
USE SCHEMA `default`;

SELECT * from sample_aggregation_first_lakeflow_etl_declarative_dlt_pipeline_wd36;
